import { $ } from "bun";

// Capture git hash and build timestamp
const gitHash = (await $`git rev-parse --short HEAD`.text()).trim();
const buildTime = new Date().toISOString();

// Write generated build-info module
const buildInfo = `// Auto-generated by scripts/build.ts — do not edit
export const BUILD_HASH = "${gitHash}";
export const BUILD_TIME = "${buildTime}";
`;

await Bun.write("utils/build-info.ts", buildInfo);
console.log(`Build info: hash=${gitHash} time=${buildTime}`);

// Run the production build
await $`bun build index.ts --outfile=dist/index.js --target=node --minify`;
console.log("Build complete: dist/index.js");
